<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<a class="brand" href="#">Moufasa project</a>
			<div class="nav-collapse">
				<ul class="nav">
					<li class="active"><a href="#">Accueil</a></li>
					<li><a href="#">fsf 1</a></li>
					<li><a href="#">Lien 2</a></li>
				</ul>
			</div><!--/.nav-collapse -->
		</div>
	</div>
</div>
